# Configure this Discovery Server
eureka:
  instance:
    metaDataMap: 
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server: 
  port: 1111 #(HTTP Port) Tomcat